# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    paths: 
      - 'file_version_info.txt'
      - 'RainClassroomAssistant.spec'
      - 'python-app.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    outputs:
      executable_path: ./dist/RainClassroomAssistant.exe
    steps:
    - name: PyInstaller Action
      uses: sayyid5416/pyinstaller@v1.6.1
      with:
        python_ver: '3.10'
        spec: 'RainClassroomAssistant.spec'
        requirements: 'requirements.txt'
    - name: Upload Executable
      uses: actions/upload-artifact@v4.4.0
      with:
        name: RainClassroomAssistant
        path: ./dist/RainClassroomAssistant.exe

  pyinstaller-build-ios:
    runs-on: macos-latest
    steps:
    - name: PyInstaller Action
      uses: sayyid5416/pyinstaller@v1.6.1
      with:
        python_ver: '3.10'
        spec: 'RainClassroomAssistant.spec'
        requirements: 'requirements.txt'
    - name: Upload Executable
      uses: actions/upload-artifact@v4.4.0
      with:
        name: RainClassroomAssistant
        path: ./dist/RainClassroomAssistant

  release:
    runs-on: ubuntu-latest
    needs: [pyinstaller-build, pyinstaller-build-ios]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: get version
        id: get_version
        run: |
          version=$(python -c "import re; f = open('file_version_info.txt', 'r'); print('v'+re.search(\"u'FileVersion', u'.*'\",f.read()).group().split(\"'\")[3])")
          echo "::set-output name=version::$version"
          echo $version > version.txt
      - name: download executable
        uses: actions/download-artifact@v4.1.8
        with:
          name: RainClassroomAssistant
          path: ./dist
      - name: download ios executable
        uses: actions/download-artifact@v4.1.8
        with:
          name: RainClassroomAssistant
          path: ./dist
      - name: calculate hash for Windows executable
        id: hash_windows
        run: |
          hash=$(sha256sum ./dist/RainClassroomAssistant.exe | cut -d ' ' -f 1)
          echo "::set-output name=hash_windows::$hash"
      - name: calculate hash for iOS executable
        id: hash_ios
        run: |
          hash=$(sha256sum ./dist/RainClassroomAssistant | cut -d ' ' -f 1)
          echo "::set-output name=hash_ios::$hash"
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./dist/RainClassroomAssistant.exe
            ./dist/RainClassroomAssistant
            version.txt
          tag_name: ${{ steps.get_version.outputs.version }}
          name: ${{ steps.get_version.outputs.version }}
          body: |
            ## hash256
            - RainClassroomAssistant.exe: ${{ steps.hash_windows.outputs.hash_windows }}

            - RainClassroomAssistant (iOS): ${{ steps.hash_ios.outputs.hash_ios }}
          draft: false
          prerelease: false